entities:

- guid: player
  name: John Johnson
  description: Your average adventurer.
- guid: key
  name: Shiny key
  description: A key that shines and opens doors.
- guid: tehom
  name: Tehom
  description: The world, needlessly cruel.
- guid: roomNorthern
  name: Northern Room
  description: The room up north, dark and cold.
- guid: roomSouthern
  name: Southern Room
  description: The room down south, lit and warm.

- guid: table
  name: Table McTableface
  description: A normal wooden table for testing non-alive entities.
  composed: [tableTop', tableLeg1, tableLeg2, tableLeg3, tableLeg4]

- guid: cat
  name: Cat the NPC
  description: Simple NPC for testing NPC creation.
  composed: [catTorso, catLegFrontLeft, catLegFrontRight, catLegBackLeft, catLegBackRight, catTail, catBrain, catEyes, catSkull, catEars, catMouth, catSkin]
